local M = {}
function M.get(colors, options)
	local ret = {
		["@none"] = { link = "None" },
		["@annotation"] = { fg = colors.accent1 },
		["@attribute"] = { fg = colors.accent1 },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@character.printf"] = { fg = colors.pastel12 },
		["@character.special"] = { fg = colors.pastel12 },
		["@comment"] = { fg = colors.fg_inactive, italic = true },
		["@comment.error"] = { fg = colors.error },
		["@comment.hint"] = { fg = colors.hint },
		["@comment.info"] = { fg = colors.info },
		["@comment.note"] = { fg = colors.hint },
		["@comment.todo"] = { fg = colors.todo },
		["@comment.warning"] = { fg = colors.warning },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { fg = colors.sec9, italic = true },
		["@constant.macro"] = { fg = colors.accent1 },
		["@constructor"] = { fg = colors.sec3 },
		["@constructor.tsx"] = { fg = colors.sec3 },
		["@diff.delta"] = { link = "GitChange" },
		["@diff.minus"] = { link = "GitDelete" },
		["@diff.plus"] = { link = "GitAdd" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { fg = colors.sec3, italic = true },
		["@function.call"] = { fg = colors.pastel15 },
		["@function.macro"] = { fg = colors.accent1 },
		["@function.method"] = { fg = colors.sec3 },
		["@function.method.call"] = { fg = colors.pastel15 },
		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.debug"] = { fg = colors.accent1 },
		["@keyword.directive"] = { fg = colors.accent1 },
		["@keyword.exception"] = { fg = colors.hue0 },
		["@keyword.function"] = { fg = colors.sec3 },
		["@keyword.import"] = { fg = colors.sec1 },
		["@keyword.operator"] = { link = "Operator" },
		["@keyword.repeat"] = { link = "Repeat" },
		["@label"] = { link = "Label" },
		["@markup"] = { link = "@none" },
		["@markup.emphasis"] = { italic = true },
		["@markup.heading"] = { link = "MarkdownHeading" },
		["@markup.link"] = { link = "MarkdownLinkText" },
		["@markup.raw"] = { link = "String" },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },
		["@module"] = { fg = colors.sec1 },
		["@module.builtin"] = { fg = colors.sec9, italic = true },
		["@namespace.builtin"] = { fg = colors.sec9, italic = true },
		["@number"] = { link = "Number" },
		["@operator"] = { link = "Operator" },
		["@property"] = { fg = colors.pastel15 },
		["@punctuation.bracket"] = { fg = colors.pastel12 },
		["@punctuation.delimiter"] = { fg = colors.pastel12 },
		["@punctuation.special"] = { fg = colors.pastel12 },
		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = colors.pastel5 },
		["@string.escape"] = { fg = colors.sec7 },
		["@string.regexp"] = { fg = colors.sec7 },
		["@tag"] = { fg = colors.sec1 },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = colors.sec3, italic = true },
		["@variable"] = { fg = colors.pastel15 },
		["@variable.builtin"] = { fg = colors.sec9, italic = true },
		["@variable.parameter"] = { fg = colors.pastel15, italic = true },
	}

	for i = 1, 6 do
		ret["@markup.heading." .. i .. ".markdown"] = { fg = colors.pastel15, bold = true }
	end
	return ret
end
return M
