local M = {}

function M.get(colors, options)
	return {
		["@none"] = { link = "none" },
		["@annotation"] = { link = "PreProc" },
		["@attribute"] = { link = "PreProc" },

		["@boolean"] = { link = "Boolean" },
		["@boolean.true"] = { link = "Boolean" },
		["@boolean.false"] = { link = "Boolean" },

		["@character"] = { link = "Character" },
		["@character.printf"] = { link = "SpecialChar" },
		["@character.special"] = { link = "SpecialChar" },

		["@comment"] = { link = "Comment" },
		["@comment.error"] = { link = "Error" },
		["@comment.hint"] = { fg = colors.C10 },
		["@comment.info"] = { fg = colors.C6 },
		["@comment.note"] = { link = "Note" },
		["@comment.todo"] = { link = "Todo" },
		["@comment.warning"] = { fg = colors.C4 },
		["@comment.documentation"] = { link = "Comment" },

		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Special" },
		["@constant.macro"] = { link = "Define" },

		["@constructor"] = { fg = colors.C8 },
		["@constructor.tsx"] = { link = "PreProc" },

		["@diff.delta"] = { link = "DiffChange" },
		["@diff.minus"] = { link = "DiffDelete" },
		["@diff.plus"] = { link = "DiffAdd" },

		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Special" },
		["@function.call"] = { link = "@function" },
		["@function.macro"] = { link = "Macro" },
		["@function.method"] = { link = "Function" },
		["@function.method.call"] = { link = "@function.method" },

		["@keyword"] = { link = "Keyword" },
		["@keyword.conditional"] = { link = "Conditional" },
		["@keyword.debug"] = { link = "Debug" },
		["@keyword.directive"] = { link = "PreProc" },
		["@keyword.exception"] = { link = "Exception" },
		["@keyword.function"] = { link = "Function" },
		["@keyword.import"] = { link = "Include" },
		["@keyword.operator"] = { link = "@operator" },
		["@keyword.repeat"] = { link = "Repeat" },
		["@keyword.return"] = { link = "Return" },
		["@keyword.storage"] = { link = "StorageClass" },

		["@markup"] = { link = "@none" },
		["@markup.emphasis"] = { italic = true },
		["@markup.environment"] = { link = "Macro" },
		["@markup.environment.name"] = { link = "Type" },
		["@markup.heading"] = { link = "Title" },
		["@markup.italic"] = { italic = true },
		["@markup.link"] = { fg = colors.C7 },
		["@markup.link.label"] = { link = "SpecialChar" },
		["@markup.link.label.symbol"] = { link = "Identifier" },
		["@markup.link.url"] = { link = "Underlined" },
		["@markup.list"] = { fg = colors.C10 },
		["@markup.list.checked"] = { fg = colors.C3 },
		["@markup.list.markdown"] = { fg = colors.C2, bold = true },
		["@markup.list.unchecked"] = { fg = colors.C6 },
		["@markup.math"] = { link = "Special" },
		["@markup.raw"] = { link = "String" },
		["@markup.raw.markdown_inline"] = { bg = colors.A2, fg = colors.C7 },
		["@markup.strikethrough"] = { strikethrough = true },
		["@markup.strong"] = { bold = true },
		["@markup.underline"] = { underline = true },

		["@module"] = { link = "Include" },
		["@module.builtin"] = { fg = colors.C0 },
		["@namespace.builtin"] = { link = "@variable.builtin" },
		["@number"] = { link = "Number" },
		["@number.float"] = { link = "Float" },
		["@operator"] = { link = "Operator" },
		["@property"] = { fg = colors.C3 },
		["@punctuation.bracket"] = { fg = colors.A4 },
		["@punctuation.delimiter"] = { fg = colors.C6 },
		["@punctuation.special"] = { fg = colors.C10 },
		["@punctuation.special.markdown"] = { fg = colors.C2 },

		["@string"] = { link = "String" },
		["@string.documentation"] = { fg = colors.C5 },
		["@string.escape"] = { fg = colors.C8 },
		["@string.regexp"] = { fg = colors.C9 },

		["@tag"] = { link = "Label" },
		["@tag.attribute"] = { link = "@property" },
		["@tag.delimiter"] = { link = "Delimiter" },
		["@tag.delimiter.tsx"] = { fg = colors.C5 },
		["@tag.tsx"] = { fg = colors.C0 },
		["@tag.javascript"] = { fg = colors.C0 },

		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "TypeBuiltin" },
		["@type.definition"] = { link = "TypeDef" },
		["@type.qualifier"] = { link = "@keyword" },

		["@variable"] = { link = "Identifier" },
		["@variable.builtin"] = { link = "Special" },
		["@variable.member"] = { link = "Field" },
		["@variable.parameter"] = { link = "Parameter" },
		["@variable.parameter.builtin"] = { fg = colors.C5 },

		["@field"] = { link = "Field" },
		["@field.key"] = { link = "Property" },
		["@method"] = { link = "Method" },
		["@method.call"] = { link = "Method" },

		["@text.literal"] = { link = "String" },
		["@text.reference"] = { link = "Identifier" },
		["@text.title"] = { link = "Title" },
		["@text.todo"] = { link = "Todo" },
		["@text.warning"] = { link = "WarningMsg" },
		["@text.danger"] = { link = "ErrorMsg" },
	}
end

return M
