local M = {}
function M.get(colors, options)
	return {
		Constant = { fg = colors.sec9 },
		String = { fg = colors.pastel5 },
		Character = { fg = colors.pastel5 },
		Number = { fg = colors.sec7 },
		Boolean = { fg = colors.sec9 },
		Float = { fg = colors.sec7 },
		Identifier = { fg = colors.pastel15 },
		Function = { fg = colors.sec3 },
		Statement = { fg = colors.def4 },
		Conditional = { fg = colors.def4 },
		Repeat = { fg = colors.def4 },
		Label = { fg = colors.def4 },
		Operator = { fg = colors.pastel12 },
		Keyword = { fg = colors.def4 },
		PreProc = { fg = colors.accent1 },
		Type = { fg = colors.sec3 },
		Structure = { fg = colors.sec3 },
		Special = { fg = colors.pastel12 },
		Todo = { fg = colors.accent8, bold = true },
		Error = { fg = colors.hue0 },
		MarkdownHeading = { fg = colors.pastel15, bold = true },
		MarkdownLinkText = { fg = colors.sec3, underline = true },
		MarkdownLinkUrl = { fg = colors.pastel12 },
		GitAdd = { fg = colors.git.add },
		GitChange = { fg = colors.git.change },
		GitDelete = { fg = colors.git.delete },
		SpellBad = { sp = colors.hue0, undercurl = true },
		SpellCap = { sp = colors.def4, undercurl = true },
		SpellLocal = { sp = colors.def4, undercurl = true },
		SpellRare = { sp = colors.def4, undercurl = true },
		Whitespace = { fg = colors.none },
	}
end
return M
